import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "../styles/globals.css";
import { PropsWithChildren } from "react";
import { cn } from "@/libs/utils";
import { estedad } from "@/libs/fonts";

const outfit = Outfit({ variable: "--outfit-font", subsets: ["latin"] });

export const metadata: Metadata = {
 title: "CTelecom Academy",
 description: "Generated by create next app",
};

type RootLayoutProps = Readonly<PropsWithChildren>;
export default function RootLayout({ children }: RootLayoutProps) {
 return (
  <html lang="fa" dir="rtl">
   <body
    className={cn(outfit.variable, estedad.variable, [
     "font-estedad",
     "min-h-lvh",
     "overflow-x-hidden",
    ])}
   >
    {children}
   </body>
  </html>
 );
}
